### PR TITLE
#1332 Comment and close the issue if the sanity check failed

### LINKED ISSUE #1332: Comment and close the issue if sanity check failed

### PR DESCRIPTION
**Pull request by langonginc**
Fix #1332

### CODE REVIEW

**Review by thekingofcity — APPROVED** [review]
LGTM

Have a test issue and we should be good to go if everything goes as expected :)

**Comment by langonginc** [comment]
How to test this? 👀

**Comment by thekingofcity** [comment]
Submit a test issue with a work having simple path and single color. If it is closed successfully, then the test passes :)

**Comment by thekingofcity** [comment]
> Submit a test issue with a work having simple path and single color. If it is closed successfully, then the test passes :)

Sorry for that. We could not test it until it was merged. Let's merge this and test it right after the merge. If something goes wrong, fix it as soon as we can :)

**Pull request merged**
